apiVersion: v1
kind: Service
metadata:
  labels:
    app: elk-objectstore-app
  name: elasticsearch
  #namespace: default
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  # nodePort: 30445
  selector:
    app: elk-objectstore-app
    component: elk-elasticsearch
  sessionAffinity: None
  type: ClusterIP
  #type: NodePort
 
