#!/bin/bash
#
# This script installs (optional, reuired) helper tools on your cluster:
# - the Kubernetes web ui
# - the HELM kubernetes package manager
#

# install kubernetes dashboard - compatible with CCE kubernetes version

# for OTC with CCE/Kubernetes <= 1.5.x
#kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.5.1/src/deploy/kubernetes-dashboard.yaml

# for OTC with CCE/Kubernetes >1.7
# the first command is required to gramt admin installation role in system
# namespace
#kubectl create clusterrolebinding your-user-cluster-admin-binding --clusterrole=cluster-admin --user=$OS_USERNAME
#kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.7.1/src/deploy/recommended/kubernetes-dashboard.yaml

# install the helm package manager server side called tiller
# it automatically installs into kube-system namespace
helm init
