apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-09-13T10:57:24Z
  labels:
    app: elk-objectstore-app
  name: kibana
  #namespace: default
spec:
  loadBalancerIP: 80.158.6.109
  ports:
  - name: http
    port: 5443
    protocol: TCP
    targetPort: 5601
  selector:
    app: elk-objectstore-app
    component: elk-kibana
  type: LoadBalancer
